#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$ROOT_DIR/Micro-XRCE-DDS"  # 实际的 CMake 项目目录
BUILD_DIR="${BUILD_DIR:-$ROOT_DIR/build}"
LOG_DIR="$BUILD_DIR/logs"
DEFAULT_CMAKE_ARGS=(
  -DUXRCE_ENABLE_GEN=ON
  -DUXRCE_BUILD_EXAMPLES=ON
  -DUXRCE_BUILD_AGENT_EXECUTABLE=ON
  -DCMAKE_INSTALL_PREFIX=../install
  -DCMAKE_INSTALL_LIBDIR=lib
  -DCMAKE_COLOR_DIAGNOSTICS=ON
)

jobs() { getconf _NPROCESSORS_ONLN 2>/dev/null || nproc 2>/dev/null || echo 4; }

# 使用 cmake 生成时间戳，确保跨平台一致性
cmake_ts() {
  local fmt="${1:-%Y-%m-%d %H:%M:%S}"
  command -v cmake >/dev/null 2>&1 || { echo "cmake 未找到" >&2; return 127; }
  local tmp
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' RETURN
  cat > "$tmp" <<CMAKE
string(TIMESTAMP _ts "${fmt}")
message("\${_ts}")
CMAKE
  cmake -P "$tmp" 2>&1
}

log() { echo "[$(cmake_ts)] $*"; }

# 计算字符串显示宽度（中文字符占2格）
_display_width() {
  local s="$1"
  # 使用 LC_ALL=C.UTF-8 确保正确的 UTF-8 字符计数
  local chars ascii
  chars=$(LC_ALL=C.UTF-8 bash -c 'echo ${#1}' _ "$s")
  ascii=$(printf '%s' "$s" | LC_ALL=C tr -cd '\0-\177' | wc -c | tr -d ' ')
  echo $((ascii + (chars - ascii) * 2))
}

# 生成居中的 banner 行
_banner_line() {
  local msg="$1"
  local cols=""
  cols=$( (stty size </dev/tty | awk '{print $2}') 2>/dev/null ) || true
  [[ -z "${cols}" || "${cols}" -le 0 ]] 2>/dev/null && [[ "${COLUMNS:-0}" -gt 0 ]] && cols="$COLUMNS"
  [[ -z "${cols}" || "${cols}" -le 0 ]] 2>/dev/null && cols="$(tput cols 2>/dev/null || true)"
  [[ -z "${cols}" || "${cols}" -le 0 ]] 2>/dev/null && cols=80
  ((cols < 20)) && cols=20

  local w=$(_display_width "$msg")
  local pad=$(((cols - w) / 2)); ((pad < 0)) && pad=0
  local right=$((cols - pad - w)); ((right < 0)) && right=0
  local left_pad right_pad
  left_pad="$(printf "%*s" "$pad" "")"
  right_pad="$(printf "%*s" "$right" "")"

  if [[ -n "${NO_COLOR:-}" ]]; then
    printf "%s%s%s" "$left_pad" "$msg" "$right_pad"
  else
    local esc=$'\033'
    printf "%s[45m%s%s%s%s[0m" "$esc" "$left_pad" "$msg" "$right_pad" "$esc"
  fi
}

run_logged() {
  mkdir -p "$LOG_DIR"
  local log_file="$LOG_DIR/${cmd}-$(cmake_ts "%Y%m%d-%H%M%S").log"
  ln -sfn "${log_file##*/}" "$LOG_DIR/latest.log"
  ln -sfn "${log_file##*/}" "$LOG_DIR/latest-${cmd}.log"

  (
    trap 'rc=$?; log "=== 结束 cmd=${cmd} rc=${rc} ==="' EXIT
    log "=== 开始 cmd=${cmd} log=${log_file} ==="
    main "$@"
  ) 2>&1 | tee -a "$log_file"
  return "${PIPESTATUS[0]}"
}

usage() {
  cat <<'EOF'
用法: ./build.sh [--no-log] [cmake|build|make|install|clean|rebuild|shapesdemo] [额外参数...]

选项:
  --no-log : 禁用日志记录（保持完整颜色输出）

命令:
- cmake      : 仅配置 (cmake -S -B)
- build      : 配置 + 编译 (默认)
- make       : 使用 Unix Makefiles 并 make -j
- install    : 编译 + 安装到 install 目录
- clean      : 清理 build 目录（保留 build/logs）
- rebuild    : clean + build（保留 build/logs）
- shapesdemo : 克隆并构建 ShapesDemo GUI (支持 --clean 参数)

示例:
  ./build.sh
  ./build.sh cmake -DCMAKE_BUILD_TYPE=Debug
  ./build.sh build -DUXRCE_ENABLE_GEN=ON
  ./build.sh --no-log build   # 保持颜色输出
  ./build.sh install
  ./build.sh shapesdemo         # 构建 ShapesDemo
  ./build.sh shapesdemo --clean # 清理后重新构建 ShapesDemo
EOF
}

# 解析 pixi.toml 依赖并生成工具列表（去重 + openjdk 映射）
get_pixi_tools() {
  awk '
    BEGIN { inside=0 }
    /^\[dependencies\]/ { inside=1; next }
    /^\[/ { if(inside) exit }
    inside && /=/ {
      sub(/#.*/, ""); gsub(/[ \t]/, "")
      split($0, a, "=")
      if (a[1] == "openjdk") { print "java"; print "javac" }
      else if (a[1] != "") print a[1]
    }
  ' "$ROOT_DIR/pixi.toml" 2>/dev/null | awk '!seen[$0]++'
}

generate_tool_report() {
  mkdir -p "$BUILD_DIR"
  local tools
  tools="$(get_pixi_tools | paste -sd ';' -)"

  cat > "$BUILD_DIR/pixi_tool_report.cmake" <<CMAKE
# Auto-generated by ./build.sh
# Source: $ROOT_DIR/pixi.toml

set(_PIXI_TOOL_REPORT_TOOLS "${tools}")

# --- colors (ANSI) ---
set(_C_RST "")
set(_C_YELLOW "")
set(_C_CYAN "")
set(_C_GREEN "")
set(_C_RED "")

if(CMAKE_COLOR_MAKEFILE AND NOT DEFINED ENV{NO_COLOR})
  string(ASCII 27 _esc)
  set(_C_RST    "\${_esc}[0m")
  set(_C_YELLOW "\${_esc}[33m")
  set(_C_CYAN   "\${_esc}[36m")
  set(_C_GREEN  "\${_esc}[32m")
  set(_C_RED    "\${_esc}[31m")
endif()

function(_pixi_first_line out_var text)
  string(REPLACE "\n" ";" _lines "\${text}")
  list(GET _lines 0 _first)
  set(\${out_var} "\${_first}" PARENT_SCOPE)
endfunction()

function(_pixi_report_exec label exe)
  if(NOT exe)
    message(STATUS "\${_C_YELLOW}\${label}\${_C_RST}: \${_C_RED}(not set)\${_C_RST}")
    return()
  endif()

  set(_p "\${exe}")
  if(EXISTS "\${_p}")
    get_filename_component(_p "\${_p}" REALPATH)
  endif()

  set(_arg "--version")
  if(label STREQUAL "java" OR label STREQUAL "javac")
    set(_arg "-version")
  endif()

  execute_process(
    COMMAND "\${exe}" "\${_arg}"
    OUTPUT_VARIABLE _o
    ERROR_VARIABLE  _e
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE _rc
  )

  if(_o STREQUAL "")
    set(_o "\${_e}")
  endif()

  if(_rc EQUAL 0 AND NOT _o STREQUAL "")
    _pixi_first_line(_v "\${_o}")
    message(STATUS "\${_C_YELLOW}\${label}\${_C_RST}: \${_C_CYAN}\${_p}\${_C_RST}  \${_C_GREEN}\${_v}\${_C_RST}")
  else()
    message(STATUS "\${_C_YELLOW}\${label}\${_C_RST}: \${_C_CYAN}\${_p}\${_C_RST}  \${_C_RED}(version unknown)\${_C_RST}")
  endif()
endfunction()

function(_pixi_report_tool name)
  unset(_p CACHE)
  find_program(_p NAMES "\${name}")
  if(NOT _p)
    message(STATUS "\${_C_YELLOW}\${name}\${_C_RST}: \${_C_RED}(not found)\${_C_RST}")
    return()
  endif()
  _pixi_report_exec("\${name}" "\${_p}")
endfunction()

message("")
if(DEFINED ENV{PIXI_TOOL_REPORT_BANNER} AND NOT "\$ENV{PIXI_TOOL_REPORT_BANNER}" STREQUAL "")
  message("\$ENV{PIXI_TOOL_REPORT_BANNER}")
else()
  message("==== Toolchain report (pixi + cmake) ====")
endif()
message(STATUS "Generator: \${CMAKE_GENERATOR}")

_pixi_report_exec("cmake" "\${CMAKE_COMMAND}")
_pixi_report_exec("make" "\${CMAKE_MAKE_PROGRAM}")
_pixi_report_exec("c_compiler" "\${CMAKE_C_COMPILER}")
_pixi_report_exec("cxx_compiler" "\${CMAKE_CXX_COMPILER}")

foreach(_t IN LISTS _PIXI_TOOL_REPORT_TOOLS)
  if(NOT _t STREQUAL "cmake")
    _pixi_report_tool("\${_t}")
  endif()
endforeach()

message(STATUS "========================================")
message(STATUS "")
CMAKE
}

cmake_configure() {
  generate_tool_report
  mkdir -p "$BUILD_DIR"
  # 临时取消 NO_COLOR 以确保颜色输出正常
  export PIXI_TOOL_REPORT_BANNER="$(unset NO_COLOR; _banner_line "Toolchain report (pixi + cmake)")"
  (cd "$BUILD_DIR" && unset NO_COLOR; cmake -S "$SRC_DIR" -B . "${DEFAULT_CMAKE_ARGS[@]}" "$@")
}

ensure_cmakelists_hook() {
  local cmakelists="$SRC_DIR/CMakeLists.txt"
  local marker="# >>> pixi tool report >>>"
  grep -qF "$marker" "$cmakelists" && return 0

  awk '
    { print }
    !done && /^project\(/ {
      print ""
      print "# >>> pixi tool report >>>"
      print "# Generated by ./build.sh. Optional so plain `cmake ..` still works."
      print "include(\"${CMAKE_BINARY_DIR}/pixi_tool_report.cmake\" OPTIONAL)"
      print "# <<< pixi tool report <<<"
      done=1
    }
  ' "$cmakelists" > "$cmakelists.tmp" && mv "$cmakelists.tmp" "$cmakelists"
}

do_clean() {
  local keep_logs="${1:-true}"
  if [[ -d "$BUILD_DIR" ]]; then
    log "   - 清理构建目录: $BUILD_DIR"
    if [[ "$keep_logs" == "true" ]]; then
      find "$BUILD_DIR" -mindepth 1 -maxdepth 1 \
        ! -name logs ! -name 'latest*.log' \
        -exec rm -rf {} + 2>/dev/null || true
    else
      rm -rf "$BUILD_DIR"
    fi
  fi

  # 清理 ShapesDemo 构建目录
  local SHAPESDEMO_BUILD="$ROOT_DIR/ShapesDemo/build"
  if [[ -d "$SHAPESDEMO_BUILD" ]]; then
    log "   - 清理 ShapesDemo 构建目录: $SHAPESDEMO_BUILD"
    if [[ "$keep_logs" == "true" ]]; then
      find "$SHAPESDEMO_BUILD" -mindepth 1 -maxdepth 1 \
        ! -name logs \
        -exec rm -rf {} + 2>/dev/null || true
    else
      rm -rf "$SHAPESDEMO_BUILD"
    fi
  fi

  # 清理项目内的 .gradle 目录
  if [[ -d "$ROOT_DIR/.gradle" ]]; then
    log "   - 删除项目 Gradle 缓存: $ROOT_DIR/.gradle"
    rm -rf "$ROOT_DIR/.gradle"
  fi

  # 清理用户级 Gradle 缓存（强制删除，不忽略错误）
  if [[ -d "$HOME/.gradle" ]]; then
    log "   - 删除用户 Gradle 缓存: $HOME/.gradle"
    rm -rf "$HOME/.gradle"
    if [[ -d "$HOME/.gradle" ]]; then
      log "   ⚠️ 警告: 无法完全删除 $HOME/.gradle，请手动清理"
    fi
  fi
}

NO_LOG=false
if [[ "${1:-}" == "--no-log" ]]; then
  NO_LOG=true
  shift
fi

cmd=${1:-build}
case "$cmd" in
  -h|--help|help) usage; exit 0 ;;
  cmake|build|make|install|clean|rebuild|shapesdemo) shift || true ;;
  *) cmd=build ;;  # 兼容 ./build.sh -DCMAKE_BUILD_TYPE=Debug
esac

main() {
  ensure_cmakelists_hook

  case "$cmd" in
    clean)
      log "🧹 清理构建产物..."
      do_clean
      log "✅ 清理完成!"
      ;;
    cmake)
      cmake_configure "$@"
      ;;
    make)
      cmake_configure -G "Unix Makefiles" "$@"
      CLICOLOR_FORCE=1 CMAKE_COLOR_DIAGNOSTICS=ON make -C "$BUILD_DIR" -j"$(jobs)"
      ;;
    rebuild)
      log "♻️  重建..."
      do_clean
      cmake_configure "$@"
      CLICOLOR_FORCE=1 CMAKE_COLOR_DIAGNOSTICS=ON cmake --build "$BUILD_DIR" --parallel "$(jobs)"
      ;;
    build)
      cmake_configure "$@"
      CLICOLOR_FORCE=1 CMAKE_COLOR_DIAGNOSTICS=ON cmake --build "$BUILD_DIR" --parallel "$(jobs)"
      ;;
    install)
      cmake_configure "$@"
      CLICOLOR_FORCE=1 CMAKE_COLOR_DIAGNOSTICS=ON cmake --build "$BUILD_DIR" --parallel "$(jobs)"
      log "📦 安装 Micro-XRCE-DDS 到: $ROOT_DIR/install"
      CLICOLOR_FORCE=1 CMAKE_COLOR_DIAGNOSTICS=ON cmake --install "$BUILD_DIR"
      log "✅ Micro-XRCE-DDS 安装完成!"

      # 构建并安装 ShapesDemo
      local SHAPESDEMO_DIR="$ROOT_DIR/ShapesDemo"
      local SHAPESDEMO_BUILD="$SHAPESDEMO_DIR/build"
      local INSTALL_PREFIX="$ROOT_DIR/install"

      if [[ -d "$SHAPESDEMO_DIR" ]]; then
        log "🎨 构建并安装 ShapesDemo..."
        mkdir -p "$SHAPESDEMO_BUILD"
        (
          cd "$SHAPESDEMO_BUILD"
          cmake .. \
            -DCMAKE_PREFIX_PATH="$INSTALL_PREFIX" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" \
            -DCMAKE_COLOR_DIAGNOSTICS=ON
          CLICOLOR_FORCE=1 CMAKE_COLOR_DIAGNOSTICS=ON cmake --build . --parallel "$(jobs)"
          cmake --install .
        )
        if [[ $? -eq 0 ]]; then
          log "✅ ShapesDemo 安装完成!"
        else
          log "⚠️ ShapesDemo 构建/安装失败"
        fi
      else
        log "⚠️ ShapesDemo 目录不存在，跳过"
      fi
      ;;
    shapesdemo)
      log "🎨 构建 ShapesDemo GUI..."
      local SHAPESDEMO_DIR="$ROOT_DIR/ShapesDemo"
      local SHAPESDEMO_BUILD="$SHAPESDEMO_DIR/build"
      local SHAPESDEMO_LOG_DIR="$SHAPESDEMO_BUILD/logs"
      local INSTALL_PREFIX="$ROOT_DIR/install"
      local do_clean=false

      # 解析 --clean 参数
      for arg in "$@"; do
        case "$arg" in
          --clean) do_clean=true ;;
        esac
      done

      # 检查 ShapesDemo 目录是否存在
      if [[ ! -d "$SHAPESDEMO_DIR" ]]; then
        log "❌ ShapesDemo 目录不存在: $SHAPESDEMO_DIR"
        log "   请先克隆仓库: git clone https://github.com/eProsima/ShapesDemo.git $SHAPESDEMO_DIR"
        return 1
      fi

      # 清理构建目录（如果指定了 --clean）
      if [[ "$do_clean" == "true" && -d "$SHAPESDEMO_BUILD" ]]; then
        log "   - 清理 ShapesDemo 构建目录..."
        find "$SHAPESDEMO_BUILD" -mindepth 1 -maxdepth 1 \
          ! -name logs \
          -exec rm -rf {} + 2>/dev/null || true
      fi

      # 创建构建和日志目录
      mkdir -p "$SHAPESDEMO_BUILD"
      mkdir -p "$SHAPESDEMO_LOG_DIR"

      local shapesdemo_log="$SHAPESDEMO_LOG_DIR/build-$(cmake_ts "%Y%m%d-%H%M%S").log"
      ln -sfn "${shapesdemo_log##*/}" "$SHAPESDEMO_LOG_DIR/latest.log"

      log "   - 日志文件: $shapesdemo_log"

      # 配置和构建（记录日志）
      (
        log "   - 配置 CMake..."
        cd "$SHAPESDEMO_BUILD"
        cmake .. \
          -DCMAKE_PREFIX_PATH="$INSTALL_PREFIX" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_COLOR_DIAGNOSTICS=ON

        log "   - 编译中..."
        CLICOLOR_FORCE=1 CMAKE_COLOR_DIAGNOSTICS=ON cmake --build . --parallel "$(jobs)"
      ) 2>&1 | tee -a "$shapesdemo_log"

      if [[ "${PIPESTATUS[0]}" -eq 0 ]]; then
        log "✅ ShapesDemo 构建完成!"
        log "   可执行文件: $SHAPESDEMO_BUILD/ShapesDemo"
      else
        log "❌ ShapesDemo 构建失败，请查看日志: $shapesdemo_log"
        return 1
      fi
      ;;
  esac
}

if [[ "$NO_LOG" == "true" ]]; then
  # 不记录日志，直接运行（保持完整颜色输出）
  main "$@"
else
  run_logged "$@"
fi
